title: Campfire Resources
description: A collection of skits, songs, and stories for Cub Scouts
theme: minima
show_downloads: true
markdown: kramdown
baseurl: "/campfire-resources"
collections:
  skits:
    output: true
    permalink: /skits/:name/
  songs:
    output: true
    permalink: /songs/:name/
  stories:
    output: true
    permalink: /stories/:name/
header_pages:
  - pages/search.html
  - skits.md
  - songs.md
  - stories.md
  - CONTRIBUTING.md